-- A
INSERT INTO USER_SDO_GEOM_METADATA VALUES(
    'FIGURY',
    'KSZTALT',
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X',0,0, 0.1),
        MDSYS.SDO_DIM_ELEMENT('Y',10,10, 0.1)        
    ),
    NULL
);

-- B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000,8192,10,2,0) FROM FIGURY;

-- C
CREATE INDEX FIGURES_INDEX
ON FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

-- D
SELECT ID
FROM FIGURY
WHERE SDO_FILTER(KSZTALT, SDO_GEOMETRY(2001, null, SDO_POINT_TYPE(3,3,null),null,null))='TRUE';

-- E
select ID
from FIGURY
WHERE SDO_RELATE(KSZTALT,
SDO_GEOMETRY(2001,null,SDO_POINT_TYPE(3,3,null),null,null),'mask= ANYINTERACT') = 'TRUE';



-- 2
-- A

SELECT * FROM MAJOR_CITIES;
SELECT * FROM COUNTRY_BOUNDARIES;

SELECT M.CITY_NAME, ROUND(SDO_NN_DISTANCE(1)) ODL
FROM MAJOR_CITIES M
WHERE SDO_NN(
    GEOM,
    (SELECT GEOM FROM major_cities WHERE CITY_NAME='Warsaw'),
    'sdo_num_res=10 unit=km',1
    ) = 'TRUE' AND CITY_NAME not like 'Warsaw';


-- B
SELECT M.CITY_NAME
FROM MAJOR_CITIES M
WHERE SDO_WITHIN_DISTANCE(
    M.GEOM,
    (SELECT GEOM FROM major_cities WHERE CITY_NAME='Warsaw'),
    'distance=100 unit=km'
    ) = 'TRUE' AND M.CITY_NAME NOT LIKE 'Warsaw';
    
-- C

SELECT M.CNTRY_NAME, M.CITY_NAME
FROM MAJOR_CITIES M
WHERE SDO_RELATE(
    M.GEOM,
    (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME LIKE 'Slovakia'),
    'mask=ANYINTERACT') = 'TRUE';
    


-- D
SELECT C.CNTRY_NAME,  ROUND(SDO_NN_DISTANCE(1)) ODL
FROM COUNTRY_BOUNDARIES C
WHERE SDO_NN
    (
        C.GEOM,
        (select GEOM from COUNTRY_BOUNDARIES where CNTRY_NAME LIKE 'Poland'),
        'unit=km',1
    ) = 'TRUE' AND C.CNTRY_NAME NOT LIKE 'Poland'
    
    AND
    
    SDO_GEOM.RELATE
    (
        C.GEOM,
        'TOUCH',
        (select GEOM from COUNTRY_BOUNDARIES where CNTRY_NAME LIKE 'Poland')
    ) = 'FALSE'
    ORDER BY 2 DESC;

    
-- 3
-- A

SELECT C.CNTRY_NAME, SDO_GEOM.SDO_LENGTH
(
    SDO_GEOM.SDO_INTERSECTION
    (
        C.GEOM,
        (select GEOM from COUNTRY_BOUNDARIES WHERE CNTRY_NAME = 'Poland'),
        1
    ),
1, 'unit=km')
FROM COUNTRY_BOUNDARIES C
WHERE SDO_RELATE
    (
        C.GEOM,
        (select GEOM from COUNTRY_BOUNDARIES where CNTRY_NAME LIKE 'Poland'),
        'mask=TOUCH'
    ) = 'TRUE';
    
-- B
SELECT A.CNTRY_NAME,
ROUND(SDO_GEOM.sdo_area(A.GEOM, 1, 'unit=SQ_KM')) POWIERZCHNIA
from COUNTRY_BOUNDARIES A
order by 1 desc;

-- C
select SDO_GEOM.SDO_AREA(
 SDO_GEOM.SDO_MBR(A.GEOM))
from MAJOR_CITIES A
where A.CITY_NAME IN ('Warsaw', 'Lodz');

-- D

select SDO_GEOM.SDO_UNION(
(select GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Poland'), 
(select GEOM FROM MAJOR_CITIES WHERE CITY_NAME='Prague')).GET_GTYPE() FROM DUAL;

-- E

select A.CITY_NAME, B.CNTRY_NAME
from MAJOR_CITIES A, COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = B.CNTRY_NAME
and
SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(B.GEOM,1), A.GEOM,1) = 
(SELECT MIN(SDO_GEOM.SDO_DISTANCE(SDO_GEOM.SDO_CENTROID(B.GEOM,1), A.GEOM,1))
from MAJOR_CITIES A, COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = B.CNTRY_NAME);

-- F

select  NAME,
SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(A.GEOM, B.GEOM, 1), 1, 'unit=km') AS DLUGOSC
from COUNTRY_BOUNDARIES A, RIVERS B
where A.CNTRY_NAME = 'Poland' AND
SDO_RELATE(A.GEOM, B.GEOM, 'MASK=OVERLAPBDYINTERSECT')='TRUE';

SELECT * FROM COUNTRY_BOUNDARIES
SELECT * FROM  MAJOR_CITIES
SELECT * FROM STREETS_AND_RAILROADS
SELECT * FROM  WATER_BODIES
SELECT * FROM  RIVERS


