-- 1
-- A

select lpad('-',2*(level-1),'|-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||
', INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
from all_types t
start with t.type_name = 'ST_GEOMETRY'
connect by prior t.type_name = t.supertype_name
and prior t.owner = t.owner;


-- B
select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON'
and m.owner = 'MDSYS'
order by 1;

-- C

CREATE TABLE MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

-- D

INSERT INTO MYST_MAJOR_CITIES
SELECT FIPS_CNTRY, CITY_NAME, ST_Point(GEOM)
FROM MAJOR_CITIES;

-- 2
-- A

SELECT * FROM MYST_MAJOR_CITIES;

INSERT INTO MYST_MAJOR_CITIES
VALUES('PL',
    'Szczyrk',
    TREAT(ST_POINT.FROM_WKT('POINT(19.036107 49.718655)', 8307) AS ST_POINT));
    
-- B

DESCRIBE RIVERS;
SELECT name, treat(ST_POINT.FROM_SDO_GEOM(GEOM) AS ST_GEOMETRY).GET_WKT() WKT
FROM rivers;

-- C
SELECT SDO_UTIL.TO_GMLGEOMETRY( ST_POINT.GET_SDO_GEOM(STGEOM)) GML
FROM MYST_MAJOR_CITIES
WHERE CITY_NAME = 'Szczyrk';

-- 3
-- A

CREATE TABLE MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

-- B
SELECT * FROM COUNTRY_BOUNDARIES;

INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT FIPS_CNTRY, CNTRY_NAME, ST_MULTIPOLYGON(GEOM)
FROM COUNTRY_BOUNDARIES;

-- C
SELECT M.STGEOM.ST_GeometryType() TYP_OBIEKTU, COUNT(CNTRY_NAME) ILE
FROM MYST_COUNTRY_BOUNDARIES M
GROUP BY M.STGEOM.ST_GeometryType();

-- D
SELECT M.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES M;

-- 4
-- A

select B.CNTRY_NAME, count(*)
from MYST_COUNTRY_BOUNDARIES B,
MYST_MAJOR_CITIES C
where B.STGEOM.ST_CONTAINS(C.STGEOM) = 1
group by B.CNTRY_NAME;

-- B

select B.CNTRY_NAME, C.CNTRY_NAME
from MYST_COUNTRY_BOUNDARIES B,
MYST_COUNTRY_BOUNDARIES C
where B.STGEOM.ST_TOUCHES(C.STGEOM) = 1 AND C.CNTRY_NAME = 'Czech Republic';

-- C
select distinct B.CNTRY_NAME, R.name
from MYST_COUNTRY_BOUNDARIES B, RIVERS R
where B.CNTRY_NAME = 'Czech Republic'
and ST_LINESTRING(R.GEOM).ST_INTERSECTS(B.STGEOM) = 1;

-- D

SELECT TREAT(A.STGEOM.ST_UNION(B.STGEOM) as ST_POLYGON).ST_AREA() CZECHOSLOWACJA
from MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
where A.CNTRY_NAME = 'Czech Republic'
and B.CNTRY_NAME = 'Slovakia';

-- E
select treat(ST_POINT.FROM_SDO_GEOM(GEOM) AS ST_GEOMETRY).GET_WKT() OBIEKT, TREAT(B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)) as ST_POLYGON).ST_GeometryType() WEGRY_BEZ
from MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
where B.CNTRY_NAME = 'Hungary'
and W.name = 'Balaton';

-- 5
-- A

EXPLAIN PLAN FOR
SELECT count(CITY_NAME)
FROM MYST_MAJOR_CITIES M, MYST_COUNTRY_BOUNDARIES C
WHERE CNTRY_NAME = 'Poland'
AND SDO_WITHIN_DISTANCE(C.STGEOM,M.STGEOM, 'distance=100 unit=km') = 'TRUE';

-- B
INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID
FROM   ALL_SDO_GEOM_METADATA T WHERE  T.TABLE_NAME = 'MAJOR_CITIES';

INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_COUNTRY_BOUNDARIES', 'STGEOM', T.DIMINFO, T.SRID
FROM   ALL_SDO_GEOM_METADATA T WHERE  T.TABLE_NAME = 'COUNTRY_BOUNDARIES';


-- C

create index MYST_MAJOR_CITIES_IDX on
MYST_MAJOR_CITIES(STGEOM)
indextype IS MDSYS.SPATIAL_INDEX;SELECT plan_table_output FROM table(dbms_xplan.display('plan_table', null, 'basic'));

create index MYST_COUNTRY_BOUNDARIES_IDX on
MYST_COUNTRY_BOUNDARIES(STGEOM)
indextype IS MDSYS.SPATIAL_INDEX;


-- D
EXPLAIN PLAN FOR
SELECT count(CITY_NAME)
FROM MYST_MAJOR_CITIES M, MYST_COUNTRY_BOUNDARIES C
WHERE CNTRY_NAME = 'Poland'
AND SDO_WITHIN_DISTANCE(C.STGEOM,M.STGEOM, 'distance=100 unit=km') = 'TRUE'

SELECT plan_table_output FROM table(dbms_xplan.display('plan_table', null, 'basic'));

SELECT * FROM TABLE(dbms_xplan.display);